[project]
name = "safex-docs"
version = "0.1.0"
description = "Safex docs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.5",
    "mkdocs-material>=9.5",
    "mkdocs-mermaid2-plugin>=1.2.3",
]
